### ISSUE TITLE
Define contraints, QA scenarios, concerns

### ISSUE THREAD

**Issue by beandkay** [skkuse-adv/2019Fall_team2#40]
We need to define the contraints, QA scenarios, concerns of current Fitts system in order to apply ADD to it later

# Contraints

# QA scenarios

# Concerns

Feel free to add your opinions!

* Note: Due date for this is until Sunday, November 24th 12:00 pm

**Comment by leemgs** [comment]
@beandkay , Good job, If you use "Grammarly" software, you can reduce typos. ^^

**Comment by leemgs** [comment]
# Geunsik's opinion (version 20191124.1040)

In my opinion, if we add deep learning to the current existing recommendation system, we will have both external components (learning on the server) and internal components (collecting data at user equipment). Overall the idea is not bad and can improve the system usability
But, performance and security can drop a bit because of the high computation and exposure of user data to the external system

### Constraints
* Security: We have to support the reliable recommendation system with a robust security facility when the recommendation system analyzes the review contents based on the deep learning system.
* The system issues the  RSA-based encrypted keys when the system has to publish a token key for new users.

### QA scenarios
| ID      | Quality Attribute | Scenario     | Associated Use Case |
|-------|---------------------|----------------|-----------------------|
| QA-1 | Performance | The existing can not support the consistently waiting time of the users to handle the increased requests of users.  |
| QA-2 | Security | Since some data are transferred with plain text, the system gives the hackers attack possibility easily.   |
| QA-3 | Scalability |  When the number of users will be increased rapidly, the existing system does not guarantee the expected performance frequently.|
| QA-4 | Maintainability |  When the additional elements (e.g., various databases such as the key-value store, no-SQL database, different database) will be expanded to handle the additional requirements from the customers, the existing results in the difficult management of the updated system as a next-generation system. | 


### Concerns
* Compatibility: When the system will be proliferated to others (e.g. shoots, animals, accessories such as a ring, a necklace, and bags as well as the existing clothes), the recommendation system must be compatible with that.
* The elements of the system have to be interconnected with a high bandwidth such as 10Gbps.
* Enabling overall system elements as a initial system.

**Comment by beandkay** [comment]
# Constraints
* An existing relational database server must be used. This server cannot be used for other purposes than hosting the database.
* A minimum of 100 simultaneous users must be supported
* The system must be reliable, due to the number of actions will be performed between user and application server, the system must support some authorization in every API calls.

# QA scenarios
| ID      | Quality Attribute | Scenario     | Associated Use Case |
|-------|---------------------|----------------|-----------------------|
| QA-1 | Performance | The system refresh time when receiving the user's request must be less than 30 seconds.  |
| QA-2 | Performance | Time for loading the images should be less than 1 minute for totals images.  |
| QA-3 | Performance | System will work as a real-time system, so the downtime must be zero for all cases and can support at least 100 users simultaneously.  |
| QA-4 | Security | Because of the point system working as the real money system, so it needs the security level like the banking system.  |
| QA-5 | Scalability |  System must be large enough to adapt to the huge amount of user data every day, mostly for image data which costs a lot of space. |
| QA-6 | Maintainability |  System must easy to update structure with no downtime for the application server. | 

# Concerns
* Establishing an overall initial system structure
* Allocate work to members of the development team, the design team.
* Leverage the team's knowledge about core technologies using in the system (Java, Kotlin, Android, ADB, ...).

**Comment by hh951125** [comment]
Comments: I agree with adding constraints about security when we upgrading the recommendation service.

For the constraints, I add about the existing Fitts point which it must be stable
# Constraints
- Stability: Fitts point must not change unintentionally without following the user's activity (ex. shopping with Fitts point)
- Security: No third party access is allowed to user's Fitts point database

# QA scenarios
- I agree with @leemgs and @beandkay 
- Associated use-cases need to be defined according to our system requirement documentation

# Concerns
- Knowledge about Data Analytics and Artificial Intelligence is a must for the developer who manages the new recommendation system.
- Python and C++ basic is compulsory for developers to be able to use TensorFlow.

**Comment by beandkay** [comment]
I close this issue, we will use this issue for future work of ADD
